name: Train Wine Quality Model CI

on:
  push:
    branches: [ main ]

jobs:
  build-train-and-upload:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode dari repositori
    - name: Checkout repository
      uses: actions/checkout@v3 # v3 untuk checkout masih aman, bisa juga diubah ke v4

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4 # direkomendasikan update juga
      with:
        python-version: '3.12'

    # 3. Install dependensi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Jalankan skrip training
    - name: Run training script
      run: python modelling.py

    # 5. Simpan artefak menggunakan versi yang benar
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4 # <-- PERBAIKAN UTAMA
      with:
        name: wine-quality-mlruns
        path: mlruns/
